version: '3'
services:

  mysql_master_1:
    image: mysql:5.7.21
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upvotes
    volumes:
      - ./docker/config/mysql_master_1.cnf:/etc/mysql/conf.d/master_1.cnf
      - ./docker/data/mysql_master_1:/var/lib/mysql
      - ./docker/logs/mysql_master_1:/var/log/mysql

  mysql_master_2:
    image: mysql:5.7.21
    ports:
      - 3308:3308
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upvotes
    volumes:
      - ./docker/config/mysql_master_2.cnf:/etc/mysql/conf.d/master_2.cnf
      - ./docker/data/mysql_master_2:/var/lib/mysql
      - ./docker/logs/mysql_master_2:/var/log/mysql

  proxysql:
    image: perconalab/proxysql:latest
    volumes:
      - ./docker/config/proxysql.cnf:/etc/proxysql.cnf
    ports:
      - 3306:3306
      - 6032:6032
    environment:
      CLUSTER_NAME: ProxySQL
      DISCOVERY_SERVICE: 127.0.0.1:2379

  pmm_server:
    image: percona/pmm-server
    ports:
      - 8000:80

